#include "core/circuit.hpp"
#include <algorithm>
#include <cmath>
#include <iostream>

namespace asic {

void Circuit::update_node_bounds(const std::vector<size_t>& connected_nodes) {
    for (size_t node : connected_nodes) {
        if (node > max_node_id) max_node_id = node;
    }
}

void Circuit::update_voltage(const std::string& name, double new_value) {
    for (auto& comp : components) {
        // Find component by name
        if (comp->name == name) {
            // Attempt to cast to a VoltageSource
            if (auto v = dynamic_cast<Passives::VoltageSource*>(comp.get())) {
                v->value = new_value;
                return;
            }
        }
    }
    std::cerr << "[libasic] Warning: Could not update voltage for component: " << name << std::endl;
}

void Circuit::export_spice(std::ostream& os) const {
    os << "* SPICE Netlist generated by libasic\n"
       << "* Continuous-Time Physical Verification Layout\n\n";
    
    for (const auto& comp : components) {
        if (auto r = dynamic_cast<const Passives::Resistor*>(comp.get())) {
            os << "R" << r->name << " " 
               << r->nodes[0] << " " << r->nodes[1] 
               << " " << r->resistance << "\n";
               
        } else if (auto v = dynamic_cast<const Passives::VoltageSource*>(comp.get())) {
            double final_val = (v->type == VoltageType::NDC) ? -std::abs(v->value) : v->value;
            std::string type_str = (v->type == VoltageType::AC) ? "AC" : "DC";
            
            os << "V" << v->name << " " 
               << v->nodes[0] << " " << v->nodes[1] 
               << " " << type_str << " " << final_val << "\n";
               
        } else if (auto m = dynamic_cast<const fet::mos*>(comp.get())) {
            std::string model_type = (m->polarity == Polarity::N_TYPE) ? "NMOS" : "PMOS";
            
            // Standard SPICE MOSFET format: M<name> D G S B <model> W=<w> L=<l>
            os << "M" << m->name << " " 
               << m->nodes[0] << " " << m->nodes[1] << " " 
               << m->nodes[2] << " " << m->nodes[3] << " " 
               << model_type << " W=" << m->width << " L=" << m->length << "\n";
               
        } else if (auto q = dynamic_cast<const bjt::npn*>(comp.get())) {
            // Standard SPICE BJT format: Q<name> C B E <model>
            os << "Q" << q->name << " " 
               << q->nodes[0] << " " << q->nodes[1] << " " << q->nodes[2] 
               << " NPN\n";
               
        } else if (auto q = dynamic_cast<const bjt::pnp*>(comp.get())) {
            os << "Q" << q->name << " " 
               << q->nodes[0] << " " << q->nodes[1] << " " << q->nodes[2] 
               << " PNP\n";
        } else if (auto c = dynamic_cast<const Passives::Capacitor*>(comp.get())) {
            // Standard SPICE Capacitor format: C<name> node+ node- <value> [IC=<val>]
            os << "C" << c->name << " " 
               << c->nodes[0] << " " << c->nodes[1] 
               << " " << c->capacitance;
            
            // Only export the initial condition if it's non-zero
            if (c->initial_voltage != 0.0) {
                os << " IC=" << c->initial_voltage;
            }
            os << "\n";
        } else if (auto p = dynamic_cast<const Passives::PulseSource*>(comp.get())) {
            // SPICE Format: V<name> N+ N- PULSE(V1 V2 Td Tr Tf Pw Per)
            os << "V" << p->name << " " 
               << p->nodes[0] << " " << p->nodes[1] 
               << " PULSE(" << p->v_initial << " " << p->v_peak << " " 
               << p->t_delay << " " << p->t_rise << " " << p->t_fall << " " 
               << p->t_pulse_width << " " << p->t_period << ")\n";
        } else if (auto tclk = dynamic_cast<const Passives::TernaryClock*>(comp.get())) {
            os << "V" << tclk->name << " " 
               << tclk->nodes[0] << " " << tclk->nodes[1] 
               << " STAIRCASE(" << tclk->v_neg << " " << tclk->v_mid << " " << tclk->v_pos << ")\n";
        } else if (auto tg = dynamic_cast<const fet::tgate*>(comp.get())) {
            // Unroll T-Gate into parallel NMOS and PMOS for SPICE
            // M<name>_N D G S B NMOS
            os << "M" << tg->name << "_N " << tg->nodes[1] << " " << tg->nodes[2] << " " 
               << tg->nodes[0] << " " << tg->nodes[4] << " NMOS W=" << tg->width_n << " L=" << tg->length << "\n";
            
            // M<name>_P D G S B PMOS
            os << "M" << tg->name << "_P " << tg->nodes[1] << " " << tg->nodes[3] << " " 
               << tg->nodes[0] << " " << tg->nodes[5] << " PMOS W=" << tg->width_p << " L=" << tg->length << "\n";
        }
    }
    
    os << "\n.end\n";
}

} // namespace asic