#include "core/circuit.hpp"
#include <algorithm>
#include <cmath>

namespace asic {

void Circuit::update_node_bounds(const std::vector<size_t>& connected_nodes) {
    for (size_t node : connected_nodes) {
        if (node > max_node_id) max_node_id = node;
    }
}

void Circuit::export_spice(std::ostream& os) const {
    os << "* SPICE Netlist generated by libasic\n"
       << "* Continuous-Time Physical Verification Layout\n\n";
    
    for (const auto& comp : components) {
        if (auto r = dynamic_cast<const Passives::Resistor*>(comp.get())) {
            os << "R" << r->name << " " 
               << r->nodes[0] << " " << r->nodes[1] 
               << " " << r->resistance << "\n";
               
        } else if (auto v = dynamic_cast<const Passives::VoltageSource*>(comp.get())) {
            double final_val = (v->type == VoltageType::NDC) ? -std::abs(v->value) : v->value;
            std::string type_str = (v->type == VoltageType::AC) ? "AC" : "DC";
            
            os << "V" << v->name << " " 
               << v->nodes[0] << " " << v->nodes[1] 
               << " " << type_str << " " << final_val << "\n";
               
        } else if (auto m = dynamic_cast<const fet::mos*>(comp.get())) {
            std::string model_type = (m->polarity == Polarity::N_TYPE) ? "NMOS" : "PMOS";
            
            // Standard SPICE MOSFET format: M<name> D G S B <model> W=<w> L=<l>
            os << "M" << m->name << " " 
               << m->nodes[0] << " " << m->nodes[1] << " " 
               << m->nodes[2] << " " << m->nodes[3] << " " 
               << model_type << " W=" << m->width << " L=" << m->length << "\n";
               
        } else if (auto q = dynamic_cast<const bjt::npn*>(comp.get())) {
            // Standard SPICE BJT format: Q<name> C B E <model>
            os << "Q" << q->name << " " 
               << q->nodes[0] << " " << q->nodes[1] << " " << q->nodes[2] 
               << " NPN\n";
               
        } else if (auto q = dynamic_cast<const bjt::pnp*>(comp.get())) {
            os << "Q" << q->name << " " 
               << q->nodes[0] << " " << q->nodes[1] << " " << q->nodes[2] 
               << " PNP\n";
        }
    }
    
    os << "\n.end\n";
}

} // namespace asic